name: Build Python bindings

on:
  push:


jobs:

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release --universal2

